site_name: Modelo de Projeto Python
repo_url: https://github.com/incolume-treinamentos/incolume.py.model-2023-03-16
repo_name: model-2023-03-16 
edit_uri: tree/dev/docs

theme:
  name: material
  language: pt-BR
  logo: asserts/img/jedi_logo.png
  favicon: asserts/img/jedi_logo.png

nav:
    - Home: 'index.md'
    - About:
      - 'HISTORY.md'
      - 'License': 'https://raw.githubusercontent.com/incolume-treinamentos/incolume.py.model-2023-03-16/main/LICENSE'
      - 'Release Notes': CHANGELOG.md
    - Installation: 'INSTALLATION.md'
    - Usage: 'usage.md'
    - Contributing: 'development.md'
    - Authors: 'CONTRIBUTORS.md'
    - API: 
      - Module Principal: 'API/principal.md'

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

watch:
   - incolume

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [incolume.py.model_2023_03_16]

extra:
  commands:
    run: incolume
